package de.htwg.se.durak.aview.gui

import javax.swing.{BorderFactory, BoxLayout, JLabel, JPanel}

class CardOnFieldGui extends JPanel with FieldGuiLabel {
  val cardOnFieldPanel = new JPanel()
  cardOnFieldPanel.setLayout(new BoxLayout(cardOnFieldPanel, BoxLayout.X_AXIS))
  cardOnFieldPanel.setBorder(BorderFactory.createEtchedBorder())
  val cardFieldLabel = new JLabel("Karten auf dem Feld:")
  cardOnFieldPanel.add(cardFieldLabel)
  cardOnFieldPanel.add(label1)
  cardOnFieldPanel.add(label2)
  cardOnFieldPanel.add(label3)
  cardOnFieldPanel.add(label4)
  cardOnFieldPanel.add(label5)
  cardOnFieldPanel.add(label6)
  cardOnFieldPanel.add(label7)
  cardOnFieldPanel.add(label8)
  cardOnFieldPanel.add(label9)
  cardOnFieldPanel.add(label10)
  cardOnFieldPanel.add(label11)
  cardOnFieldPanel.add(label12)
  cardOnFieldPanel.add(label13)
  cardOnFieldPanel.add(label14)
  cardOnFieldPanel.add(label15)
  cardOnFieldPanel.add(label16)
  cardOnFieldPanel.add(label17)
  cardOnFieldPanel.add(label18)
  cardOnFieldPanel.add(label19)
  cardOnFieldPanel.add(label20)
  cardOnFieldPanel.add(label21)
  cardOnFieldPanel.add(label22)
  cardOnFieldPanel.add(label23)
  cardOnFieldPanel.add(label24)
  cardOnFieldPanel.add(label25)
  cardOnFieldPanel.add(label26)
  cardOnFieldPanel.add(label27)
  cardOnFieldPanel.add(label28)
  cardOnFieldPanel.add(label29)
  cardOnFieldPanel.add(label30)
  cardOnFieldPanel.add(label31)
  cardOnFieldPanel.add(label32)

  add(cardOnFieldPanel)
}
