package de.htwg.se.durak.aview.gui

import javax.swing._

class PlayerFieldGui extends JPanel with FieldGuiLabel {
  val playerPanel = new JPanel()

  playerPanel.setLayout(new BoxLayout(playerPanel, BoxLayout.X_AXIS))
  playerPanel.setBorder(BorderFactory.createEtchedBorder())
  playerPanel.add(label1)
  playerPanel.add(label2)
  playerPanel.add(label3)
  playerPanel.add(label4)
  playerPanel.add(label5)
  playerPanel.add(label6)
  playerPanel.add(label7)
  playerPanel.add(label8)
  playerPanel.add(label9)
  playerPanel.add(label10)
  playerPanel.add(label11)
  playerPanel.add(label12)
  playerPanel.add(label13)
  playerPanel.add(label14)
  playerPanel.add(label15)
  playerPanel.add(label16)
  playerPanel.add(label17)
  playerPanel.add(label18)
  playerPanel.add(label19)
  playerPanel.add(label20)
  playerPanel.add(label21)
  playerPanel.add(label22)
  playerPanel.add(label23)
  playerPanel.add(label24)
  playerPanel.add(label25)
  playerPanel.add(label26)
  playerPanel.add(label27)
  playerPanel.add(label28)
  playerPanel.add(label29)
  playerPanel.add(label30)
  playerPanel.add(label31)
  playerPanel.add(label32)
  add(playerPanel)
}
